services:
  postgres:
    env_file:
      - local.env
    container_name: usage-billing-postgres-dev
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - billing-network-dev

  billing-service:
    env_file:
      - local.env
    container_name: usage-billing-service-dev
    ports:
      - "8080:8080"
    networks:
      - billing-network-dev

  sonarqube:
    env_file:
      - local.env

  sonarqube-db:
    env_file:
      - local.env

volumes:
  postgres-data-dev:
    driver: local

networks:
  billing-network-dev:
    driver: bridge
