package com.microservice.billing.mapper;

import com.microservice.billing.controller.UsageEventDto;
import com.microservice.billing.domain.UsageEvent;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

/**
 * MapStruct mapper for transforming UsageEvent entities to DTOs and vice versa.
 * MapStruct generates the implementation at compile time.
 * 
 * This replaces the manual mapper implementation, reducing boilerplate while
 * maintaining type safety and performance.
 */
@Mapper(componentModel = "spring")
public interface UsageEventMapper {

    /**
     * Maps a UsageEvent entity to a UsageEventDto.
     * 
     * @param event the entity to map
     * @return the DTO representation
     */
    UsageEventDto toDto(UsageEvent event);

    /**
     * Maps a UsageEventDto to a UsageEvent entity.
     * Note: ID is ignored when creating entity from DTO (ID is generated by database).
     * 
     * @param dto the DTO to map
     * @return the entity representation
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    UsageEvent toEntity(UsageEventDto dto);

    /**
     * Maps a list of UsageEvent entities to a list of UsageEventDto.
     * MapStruct automatically generates this from the single entity mapper.
     * 
     * @param events the list of entities to map
     * @return the list of DTOs
     */
    List<UsageEventDto> toDtoList(List<UsageEvent> events);

    /**
     * Maps a list of UsageEventDto to a list of UsageEvent entities.
     * MapStruct automatically generates this from the single entity mapper.
     * 
     * @param dtos the list of DTOs to map
     * @return the list of entities
     */
    List<UsageEvent> toEntityList(List<UsageEventDto> dtos);
}
